services:
  jvdme:
    container_name: jvdme
    image: nginx:alpine
    volumes:
      - ./html:/usr/share/nginx/html
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.jvdme.entrypoints=websecure
      - traefik.http.routers.jvdme.rule=Host(`jvd.me`)
      - traefik.http.routers.jvdme.middlewares=default-headers@file
      - traefik.http.services.jvdme.loadbalancer.server.port=80
    networks:
      - proxy

networks:
  proxy:
    external: true
