services:
  syncthing:
    image: lscr.io/linuxserver/syncthing:latest
    container_name: syncthing
    hostname: syncthing
    environment:
      - PUID=3001
      - PGID=3000
      - UMASK=002
      - TZ=Europe/Brussels
    volumes:
      - ./config:/config
      - /mnt/syncthing:/data
    ports:
      # - 8384:8384
      - 22000:22000/tcp
      - 22000:22000/udp
      - 21027:21027/udp
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.syncthing.entrypoints=websecure"
      - "traefik.http.routers.syncthing.rule=Host(`syncthing.internal.vandijck.xyz`)"
      - "traefik.http.routers.syncthing.middlewares=secured@file"
      - "traefik.http.services.syncthing.loadbalancer.server.port=8384"
    restart: unless-stopped
    networks:
      - proxy

networks:
  proxy:
    external: true
